name: Keep Render Services Alive
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 13-21 * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service 1
        run: curl -s -o /dev/null -w "Service 1: %{http_code}\n" "${{ secrets.RENDER_URL_1 }}"
      - name: Ping Render service 2
        run: curl -s -o /dev/null -w "Service 2: %{http_code}\n" "${{ secrets.RENDER_URL_2 }}"
# trigger
